# -*- mode: python ; coding: utf-8 -*-

import datetime
import json
import os
import pathlib
import re
import sys

from PyInstaller.utils.hooks import collect_all


def normalize_version(value):
    value = (value or "").strip()
    if not value:
        return "dev"
    if value.startswith("v") or value.startswith("ci-") or value.startswith("dev-"):
        return value
    if re.fullmatch(r"\d+\.\d+\.\d+(?:[-.][0-9A-Za-z.-]+)?", value):
        return f"v{value}"
    return value


root = pathlib.Path.cwd()
sys.path.insert(0, str(root))
from protocol import PROTOCOL_VERSION

app_version = normalize_version(
    os.environ.get("VUNMIX_VERSION") or os.environ.get("VERSION") or "dev"
)
git_sha = (
    os.environ.get("VUNMIX_GIT_SHA")
    or os.environ.get("GITHUB_SHA")
    or "unknown"
).strip()
build_date = (
    os.environ.get("VUNMIX_BUILD_DATE")
    or datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
).strip()

(root / "_build_metadata.py").write_text(
    "# Generated by VuNMix.spec; do not commit.\n"
    f"APP_VERSION = {app_version!r}\n"
    f"GIT_SHA = {git_sha!r}\n"
    f"BUILD_DATE = {build_date!r}\n",
    encoding="utf-8",
)
(root / "build-metadata.json").write_text(
    json.dumps(
        {
            "version": app_version,
            "git_sha": git_sha,
            "build_date": build_date,
            "protocol_version": PROTOCOL_VERSION,
        },
        indent=2,
    ),
    encoding="utf-8",
)

print(f"VuNMix desktop version: {app_version}")
print(f"VuNMix desktop git SHA: {git_sha}")
print(f"VuNMix desktop build date: {build_date}")
print(f"VuNMix protocol version: {PROTOCOL_VERSION}")

# esptool ships ESP32-family flasher stubs as package data (JSON/binary files).
# PyInstaller does not include these automatically when only hidden imports are
# listed, so collect the complete package to keep firmware updates functional
# in the windowed VuNMix build.
esptool_datas, esptool_binaries, esptool_hiddenimports = collect_all("esptool")


a = Analysis(
    ["vunmix.py"],
    pathex=[],
    binaries=esptool_binaries,
    datas=[("assets", "assets"), ("build-metadata.json", ".")] + esptool_datas,
    hiddenimports=[
        "win32api",
        "win32con",
        "win32gui",
        "win32ui",
    ] + esptool_hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="VuNMix",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=["assets\\icon.ico"],
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="VuNMix",
)
